#!/usr/bin/env bash
# A script that Installs HAproxy on ubuntu 20.04 server

# Store IP addresses in variables
web_01_ip="3.80.19.9"
web_02_ip="54.146.68.236"

# Install HAproxy
sudo apt update
sudo apt install -y haproxy

# Configure HAproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo rm /etc/haproxy/haproxy.cfg
sudo touch /etc/haproxy/haproxy.cfg

# Add configuration to HAproxy config file
sudo sh -c "cat > /etc/haproxy/haproxy.cfg << EOL
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 $web_01_ip:80 check
    server web-02 $web_02_ip:80 check

EOL"

# Configure init script for HAproxy
sudo systemctl enable haproxy

# Restart HAproxy
sudo systemctl restart haproxy
