#!/usr/bin/env bash
#Debugging Script
# Remove the default Nginx configuration file for port 8080
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration file for port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx server to use the new configuration file
service nginx restart
