#!/usr/bin/env bash
# A bash script that changes nginx port to 80
sudo sed -i 's/listen 8080 default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
# restart Nginx
sudo service nginx restart
sudo service stop
